### ISSUE TITLE
empty windows package

### ISSUE THREAD

**Issue by adriendelsalle** [conda-forge/json_schema_validator-feedstock#1]
Hi! Thanks for this recipe, I encounter trouble to use Windows package.
Thanks!

**Issue**
---
 The windows package seems to be empty. The recipe is missing a build.bat file to handle Windows packages: bld.sh is the only build file in the recipe directory.

**Environment**
---
Running on Windows10
Name | Version | Build | Channel
| ------------- |:-------------:|:-----:|:-----:|
conda | 4.8.3 | py36h9f0ad1d_1 | conda-forge
nlohmann_json | 3.7.3 | he025d50_1 | conda-forge
json_schema_validator | 2.0.0 | h6538335_0 | conda-forge

**Comment by wolfv** [comment]
Do you want to make a PR? I can help review and merge it

**Comment by adriendelsalle** [comment]
Hi @wolfv 
Sure I will do that, thanks!

**Comment by adriendelsalle** [comment]
@wolfv 
We have a packaging problem on [nlohmann_json](https://github.com/conda-forge/nlohmann_json-feedstock) to solve before updating this feedstock.

`json_schema_validator` requires NLohmann's JSON version 3.8.0 or higher
Conda-forge v3.8.0 and v3.9.0 builds are failing according to the bot messages in [PRs](https://github.com/conda-forge/nlohmann_json-feedstock/pulls).
